// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadImage(arg1) {
  return window['go']['main']['App']['DownloadImage'](arg1);
}

export function GetDay() {
  return window['go']['main']['App']['GetDay']();
}

export function GetMonth() {
  return window['go']['main']['App']['GetMonth']();
}

export function GetTime() {
  return window['go']['main']['App']['GetTime']();
}

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function UpdateWeather() {
  return window['go']['main']['App']['UpdateWeather']();
}
