// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function DownloadImage(arg1:string):Promise<string>;

export function GetDay():Promise<string>;

export function GetMonth():Promise<string>;

export function GetTime():Promise<string>;

export function GetWeather():Promise<parser.WeatherInfo>;

export function UpdateWeather():Promise<parser.WeatherInfo>;
